app_login:
    path: /login
    controller: App\Controller\SecurityController::login
app_login_check:
    path: /login_check
app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
projets:
    path: /
    controller: App\Controller\ProjetController::projets
addprojet:
    path: /projets/add
    controller: App\Controller\ProjetController::add
iut_add:
    path: '/iut/add'
    controller: App\Controller\IutController::add
iut_add_api:
    path: '/api/iut/add'
    controller: App\Controller\IutController::api
iut_del_api:
    path: '/api/iut/del'
    controller: App\Controller\IutController::apidel
profil:
    path: '/profil/{id}'
    controller: App\Controller\UserController::profil
    defaults:
        id: 0
profil_api:
    path: '/api/profil/{id}'
    controller: App\Controller\UserController::api
add_user_api:
    path: '/api/user/add'
    controller: App\Controller\UserController::apiadd
del_user_api:
    path: '/api/user/del'
    controller: App\Controller\UserController::apidel
ac_add:
    path: '/ac/add'
    controller: App\Controller\AcController::add
ac_add_api:
    path: '/api/ac/add'
    controller: App\Controller\AcController::api
ac_del_api:
    path: '/api/ac/del'
    controller: App\Controller\AcController::apidel
delete_comment:
    path: '/profil/note/delete/{idNote}/{idUser}/{idPage}'
    controller: App\Controller\UserController::delete_comment
delete_projet:
    path: '/projet/delete/{idProjet}/{idUser}/{idPage}'
    controller: App\Controller\ProjetController::delete_projet
edit_projet:
    path: '/projet/edit/{idProjet}/{idUser}/{idPage}'
    controller: App\Controller\ProjetController::edit_projet
recherche:
    path: '/search/{nom}'
    controller: App\Controller\ProjetController::search
adminpanel:
    path: '/adminpanel'
    controller: App\Controller\UserController::adminpanel